name: Lint

on:
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Scan terraform files with tfsec
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ github.token }}
          tfsec_args: --ignore-hcl-errors

      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@v1.17.0
        with:
          github_token: ${{ secrets.github_token }}
          filter_mode: nofilter
          fail_on_error: true
          tfsec_flags: --ignore-hcl-errors

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform validate
        uses: dflook/terraform-validate@v1.46.0

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.46.0
